### PR TITLE
Fix roman numeral test for 1991

### PR DESCRIPTION
**Pull request by jacksonweekes**

### CODE REVIEW

**Comment by ghost** [comment]
Beat you to it. :wink:

https://github.com/UNEcosc250/firststeps/pull/2

**Comment by jacksonweekes** [comment]
Haha so you did, shows me for not looking at the open pull requests.

**Comment by ghost** [comment]
Not sure if it's getting pulled anyways, the issue might have been intentional.

**Comment by jacksonweekes** [comment]
Hmm think it was probably more likely a mistake, maybe Will is just trying to mess with everyone though :-p

**Pull request closed without merging**
